; Auto-generated. Do not edit!


(cl:in-package exercise3-msg)


;//! \htmlinclude FactorialGoal.msg.html

(cl:defclass <FactorialGoal> (roslisp-msg-protocol:ros-message)
  ((order
    :reader order
    :initarg :order
    :type cl:integer
    :initform 0))
)

(cl:defclass FactorialGoal (<FactorialGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FactorialGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FactorialGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name exercise3-msg:<FactorialGoal> is deprecated: use exercise3-msg:FactorialGoal instead.")))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <FactorialGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader exercise3-msg:order-val is deprecated.  Use exercise3-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FactorialGoal>) ostream)
  "Serializes a message object of type '<FactorialGoal>"
  (cl:let* ((signed (cl:slot-value msg 'order)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FactorialGoal>) istream)
  "Deserializes a message object of type '<FactorialGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'order) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FactorialGoal>)))
  "Returns string type for a message object of type '<FactorialGoal>"
  "exercise3/FactorialGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FactorialGoal)))
  "Returns string type for a message object of type 'FactorialGoal"
  "exercise3/FactorialGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FactorialGoal>)))
  "Returns md5sum for a message object of type '<FactorialGoal>"
  "fa193cc5c689c8516842596a1268cc71")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FactorialGoal)))
  "Returns md5sum for a message object of type 'FactorialGoal"
  "fa193cc5c689c8516842596a1268cc71")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FactorialGoal>)))
  "Returns full string definition for message of type '<FactorialGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int64 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FactorialGoal)))
  "Returns full string definition for message of type 'FactorialGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int64 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FactorialGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FactorialGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FactorialGoal
    (cl:cons ':order (order msg))
))
