// Generated by gencpp from file exercise3/FactorialActionGoal.msg
// DO NOT EDIT!


#ifndef EXERCISE3_MESSAGE_FACTORIALACTIONGOAL_H
#define EXERCISE3_MESSAGE_FACTORIALACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <exercise3/FactorialGoal.h>

namespace exercise3
{
template <class ContainerAllocator>
struct FactorialActionGoal_
{
  typedef FactorialActionGoal_<ContainerAllocator> Type;

  FactorialActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FactorialActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::exercise3::FactorialGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::exercise3::FactorialActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise3::FactorialActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FactorialActionGoal_

typedef ::exercise3::FactorialActionGoal_<std::allocator<void> > FactorialActionGoal;

typedef boost::shared_ptr< ::exercise3::FactorialActionGoal > FactorialActionGoalPtr;
typedef boost::shared_ptr< ::exercise3::FactorialActionGoal const> FactorialActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise3::FactorialActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise3::FactorialActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise3::FactorialActionGoal_<ContainerAllocator1> & lhs, const ::exercise3::FactorialActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise3::FactorialActionGoal_<ContainerAllocator1> & lhs, const ::exercise3::FactorialActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae1fcd8f6cdb19bd423f67ae6608bcfa";
  }

  static const char* value(const ::exercise3::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae1fcd8f6cdb19bdULL;
  static const uint64_t static_value2 = 0x423f67ae6608bcfaULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise3/FactorialActionGoal";
  }

  static const char* value(const ::exercise3::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FactorialGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: exercise3/FactorialGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int64 order\n"
;
  }

  static const char* value(const ::exercise3::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactorialActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise3::FactorialActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise3::FactorialActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::exercise3::FactorialGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE3_MESSAGE_FACTORIALACTIONGOAL_H
