// Generated by gencpp from file exercise3/FactorialFeedback.msg
// DO NOT EDIT!


#ifndef EXERCISE3_MESSAGE_FACTORIALFEEDBACK_H
#define EXERCISE3_MESSAGE_FACTORIALFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise3
{
template <class ContainerAllocator>
struct FactorialFeedback_
{
  typedef FactorialFeedback_<ContainerAllocator> Type;

  FactorialFeedback_()
    : sequence()  {
    }
  FactorialFeedback_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::exercise3::FactorialFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise3::FactorialFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FactorialFeedback_

typedef ::exercise3::FactorialFeedback_<std::allocator<void> > FactorialFeedback;

typedef boost::shared_ptr< ::exercise3::FactorialFeedback > FactorialFeedbackPtr;
typedef boost::shared_ptr< ::exercise3::FactorialFeedback const> FactorialFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise3::FactorialFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise3::FactorialFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise3::FactorialFeedback_<ContainerAllocator1> & lhs, const ::exercise3::FactorialFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise3::FactorialFeedback_<ContainerAllocator1> & lhs, const ::exercise3::FactorialFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise3::FactorialFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43834c71ae4b726371cabcee1e961700";
  }

  static const char* value(const ::exercise3::FactorialFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43834c71ae4b7263ULL;
  static const uint64_t static_value2 = 0x71cabcee1e961700ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise3::FactorialFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise3/FactorialFeedback";
  }

  static const char* value(const ::exercise3::FactorialFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise3::FactorialFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int64[] sequence\n"
;
  }

  static const char* value(const ::exercise3::FactorialFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise3::FactorialFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactorialFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise3::FactorialFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise3::FactorialFeedback_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE3_MESSAGE_FACTORIALFEEDBACK_H
