// Generated by gencpp from file exercise3/FactorialGoal.msg
// DO NOT EDIT!


#ifndef EXERCISE3_MESSAGE_FACTORIALGOAL_H
#define EXERCISE3_MESSAGE_FACTORIALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise3
{
template <class ContainerAllocator>
struct FactorialGoal_
{
  typedef FactorialGoal_<ContainerAllocator> Type;

  FactorialGoal_()
    : order(0)  {
    }
  FactorialGoal_(const ContainerAllocator& _alloc)
    : order(0)  {
  (void)_alloc;
    }



   typedef int64_t _order_type;
  _order_type order;





  typedef boost::shared_ptr< ::exercise3::FactorialGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise3::FactorialGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FactorialGoal_

typedef ::exercise3::FactorialGoal_<std::allocator<void> > FactorialGoal;

typedef boost::shared_ptr< ::exercise3::FactorialGoal > FactorialGoalPtr;
typedef boost::shared_ptr< ::exercise3::FactorialGoal const> FactorialGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise3::FactorialGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise3::FactorialGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise3::FactorialGoal_<ContainerAllocator1> & lhs, const ::exercise3::FactorialGoal_<ContainerAllocator2> & rhs)
{
  return lhs.order == rhs.order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise3::FactorialGoal_<ContainerAllocator1> & lhs, const ::exercise3::FactorialGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise3::FactorialGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise3::FactorialGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise3::FactorialGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise3::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa193cc5c689c8516842596a1268cc71";
  }

  static const char* value(const ::exercise3::FactorialGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa193cc5c689c851ULL;
  static const uint64_t static_value2 = 0x6842596a1268cc71ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise3::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise3/FactorialGoal";
  }

  static const char* value(const ::exercise3::FactorialGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise3::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int64 order\n"
;
  }

  static const char* value(const ::exercise3::FactorialGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise3::FactorialGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactorialGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise3::FactorialGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise3::FactorialGoal_<ContainerAllocator>& v)
  {
    s << indent << "order: ";
    Printer<int64_t>::stream(s, indent + "  ", v.order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE3_MESSAGE_FACTORIALGOAL_H
